---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 5
  name: infrastructure
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/artem-usenko-quarks-tech/minikube-argo.git
  - https://charts.bitnami.com/bitnami 
