---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rabbitmq
  namespace: argocd
spec:
  destination:
    namespace: rabbitmq
    server: https://kubernetes.default.svc
  source:
    chart: rabbitmq
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 11.16.2
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    syncPolicy:
      automated: {}
