---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
spec:
  destination:
    server: https://kubernetes.default.svc
  project: infrastructure
  source:
    path: components/applications/
    repoURL: https://github.com/ArataEM/minikube-argo.git
    targetRevision: HEAD
