---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infrastructure
spec:
  generators:
  - list:
      elements:
      - application: rabbitmq
  template:
    metadata:
      name: '{{application}}'
      namespace: argocd
    spec:
      project: infrastructure
      source:
        repoURL: https://github.com/ArataEM/minikube-argo.git
        targetRevision: HEAD
        path: components/applications/{{application}}
      destination:
        server: https://kubernetes.default.svc
