---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: namespaces
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
  project: cluster-project
  source:
    path: namespaces/
    repoURL: https://github.com/ArataEM/minikube-argo.git
    targetRevision: HEAD
