---
project: infrastructure

namespaces:
  - argocd
  - rabbitmq
  - monitoring
  - gatekeeper-system

applications:
  - name: rabbitmq
    namespace: rabbitmq
    chart: rabbitmq
    targetRevision: 11.16.2
    repoURL: https://charts.bitnami.com/bitnami
  - name: gatekeeper
    namespace: gatekeeper-system
    chart: gatekeeper
    targetRevision: 3.12.0
    repoURL: https://open-policy-agent.github.io/gatekeeper/charts
