---
project: infrastructure

namespaces:
  - rabbitmq
  - monitoring

applications:
  - name: rabbitmq
    namespace: rabbitmq
    chart: rabbitmq
    targetRevision: 11.16.2
    repoURL: https://charts.bitnami.com/bitnami
