---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  generation: 5
  name: namespaces
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: 'namespace'
  destinations:
  - name: in-cluster
    namespace: '*'
    server: https://kubernetes.default.svc
  orphanedResources:
    warn: true
  sourceRepos:
  - https://github.com/ArataEM/minikube-argo
